version: "3.3"
services:
   webpython:
      image: "webapp:v2"
      ports:
        - target: 8080
          published: 8080
      networks:
        - web-net
      depends_on:
        - redis

   redis:
      image: "redis:alpine"
      networks:
        - web-net

networks:
   web-net:

